spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sscsi-local
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
