spring:
  jta:
    enabled: true
    atomikos:
      datasource:
        primary:
          url: jdbc:mysql://localhost:3306/sscsi-local?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: 123456
        secondary:
          url: jdbc:mysql://localhost:3306/dg-mcs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: 123456
#SQL 输出
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        #JTA 与 JPA处理事务
        transaction:
          jta:
            platform: com.ajc.seata.config.AtomikosJtaPlatform
      javax:
        persistence:
          transactionType: JTA  #指明事务处理类型