server:
  servlet:
    context-path: /redis
  port: 8181

spring:
  redis:
    host: 172.28.28.20
    port: 40130
    password: redis666666
    timeout: 6000
    database: 5
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
  cache:
    type: caffeine
    cache-names: caffeine-cache
    caffeine:
      spec: maximumSize=1024,refreshAfterWrite=60s


