spring:
  thymeleaf:
    cache: false
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#    encoding: UTF-8
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML
